[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
lending_app = "4aWe37Q3zNvTAHw2ctkGgwHCZTbSSgpEcqvph4ve7ctg"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=ff338341-babd-4354-82c0-e8853c64fa66"
wallet = "./my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
