[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
lending_app = "F6Laudmy1RaE4kdwTAtKCks3Hf4X5Be8RH9z63dUMVMi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "C:/Users/Piyush/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
